// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Group6.NET1704.SW392.AIDiner.DAL.Models
{
    public partial class User
    {
        public User()
        {
            Orders = new HashSet<Order>();
            WishLists = new HashSet<WishList>();
        }

        public int Id { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public DateTime? Dob { get; set; }
        public string PhoneNumber { get; set; }
        public int? RoleId { get; set; }
        public DateTime? CreateAt { get; set; }
        public string Address { get; set; }
        public bool Status { get; set; }
        public string Avatar { get; set; }

        public virtual Role Role { get; set; }
        public virtual ICollection<Order> Orders { get; set; }
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}